debug: example.cpp
	g++ -g -Wall -o example-debug example.cpp -lminiini-dbg
	g++ -g -Wall -o example-stl-debug example-stl.cpp -lminiini-dbg

optimized: example.cpp
	g++ -O3 -o example-optimized example.cpp -lminiini
	g++ -O3 -o example-stl-optimized example-stl.cpp -lminiini

clean:
	rm -f example.o example-debug example

	






