debug: example.cpp
	g++ -g -Wall -o example-debug example.cpp -lminiini-dbg

optimized: example.cpp
	g++ -O3 -o example-optimized example.cpp -lminiini

clean:
	rm -f example.o example-debug example








